### ISSUE TITLE
Add tooling for `janet_def` to cjanet

### ISSUE THREAD

**Issue by pepe** [janet-lang/spork#129]
Probably similar to what we do with `*cfun-list*` for functions, which will be registered in the environment automatically in the `module-entry`.

Would you be in favor of such a change?

**Comment by bakpakin** [comment]
Yes, does make sense. Basically any boilerplate generation is worth considering adding to cjanet.

CJanet isn't really a proper language or frontend, rather it is a collection of functions and macros for C code generation, and there isn't any desire to prevent the "abstraction" from leaking through too much. It is more a better preprocessor rather than a custom to-C transpiler.

**Comment by pepe** [comment]
I am pleased you are saying your view on cjanet and its purpose. Especially as it is similar to what I have come to.

The second paragraph is also a good base for the description.

I will make PR with the `janet_def` addition and some essential Mendoza documentation.
